In [1]:
from tqdm import tqdm
import torch
import wandb
import torch.nn as nn
from torchvision import models
from data_loading.data_loader import *
from data_loading.transforming import *

device = torch.device("cuda")
loaded_data = load_all_data()
EPOCHS = 100
model = models.resnet18(pretrained=True).to(device)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 2)
model.to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
PROJECT_NAME = "Face-Mask-Detection-PT-V2"

In [2]:
wandb.init(project=PROJECT_NAME, name="testing")
for _ in range(EPOCHS):
    for data, label in loaded_data:
        data = data.to(device)
        label = label.to(device)
        preds = model(data.float())
        preds = preds.to(device)
        loss = criterion(preds, label)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        wandb.log({"loss": loss.item()})

In [3]:
preds

tensor([[  1.1146,  -1.1714],
        [  1.0796,  -1.1722],
        [  1.1535,  -1.1866],
        [  1.1995,  -1.2258],
        [  1.0994,  -1.1772],
        [  1.2263,  -1.2575],
        [  1.1421,  -1.1807],
        [  1.1199,  -1.1824],
        [  1.3695,  -1.3843],
        [  1.1362,  -1.1866],
        [ 26.5804, -23.0414],
        [  1.2282,  -1.2329],
        [  1.1154,  -1.1794],
        [  1.1162,  -1.1710]], device='cuda:0', grad_fn=<AddmmBackward>)

In [4]:
label

tensor([0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0], device='cuda:0')

In [5]:
torch.round(preds)

tensor([[  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.],
        [ 27., -23.],
        [  1.,  -1.],
        [  1.,  -1.],
        [  1.,  -1.]], device='cuda:0', grad_fn=<RoundBackward>)

In [6]:
torch.round(preds[0])

tensor([ 1., -1.], device='cuda:0', grad_fn=<RoundBackward>)

In [7]:
torch.argmax(torch.round(preds[0]))

tensor(0, device='cuda:0')

In [8]:
label[0]

tensor(0, device='cuda:0')

In [9]:
index = 0
print(torch.argmax(torch.round(preds[0])))
print(label[0])

In [10]:
index = 1
print(torch.argmax(torch.round(preds[0])))
print(label[0])

In [11]:
index = 2
print(torch.argmax(torch.round(preds[0])))
print(label[0])

In [12]:
index = 2
print(torch.argmax(torch.round(preds[index])))
print(label[index])

In [13]:
index = 3
print(torch.argmax(torch.round(preds[index])))
print(label[index])

In [14]:
index = 50
print(torch.argmax(torch.round(preds[index])))
print(label[index])

In [15]:
index = 1
print(torch.argmax(torch.round(preds[index])))
print(label[index])

In [16]:
index = 2
print(torch.argmax(torch.round(preds[index])))
print(label[index])

In [17]:
for index in range(30):
    print(torch.argmax(torch.round(preds[index])))
    print(label[index])
    print('\n')

In [18]:
from tqdm import tqdm
import torch
import wandb
import torch.nn as nn
from torchvision import models
from data_loading.data_loader import *
from data_loading.transforming import *

device = torch.device("cuda")
loaded_data = load_data()
EPOCHS = 100
model = models.resnet18(pretrained=True).to(device)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 2)
model.to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
PROJECT_NAME = "Face-Mask-Detection-PT-V2"

In [19]:
from data_loading.data_loader import *
from data_loading.transforming import *
import torch
import torch.nn as nn

In [20]:
data = load_data()

In [21]:
def other_loading_data_proccess(data):
    print(len(data))
    X = []
    y = []
    print('going through the data..')
    for d in data:
        X.append(d[0])
        y.append(d[1])
    print('splitting the data')
    VAL_SPLIT = 0.25
    VAL_SPLIT = len(X)*VAL_SPLIT
    VAL_SPLIT = int(VAL_SPLIT)
    X_train = X[:-VAL_SPLIT]
    y_train = y[:-VAL_SPLIT]
    X_test = X[-VAL_SPLIT:]
    y_test = y[-VAL_SPLIT:]
    print('turning data to tensors')
    X_train = torch.from_numpy(np.array(X_train))
    print(len(X_train))
    y_train = torch.from_numpy(np.array(y_train))
    print(len(y_train))
    X_test = torch.from_numpy(np.array(X_test))
    print(len(X_test))
    y_test = torch.from_numpy(np.array(y_test))
    print(len(y_test))
    return [X_train,X_test,y_train,y_test]

In [22]:
other_loading_data_proccess(data)

[tensor([[[[255, 255, 255],
           [253, 255, 255],
           [255, 255, 254],
           ...,
           [155, 176, 193],
           [157, 182, 199],
           [138, 173, 189]],
 
          [[255, 255, 255],
           [253, 255, 255],
           [255, 255, 254],
           ...,
           [149, 174, 190],
           [143, 168, 184],
           [132, 161, 178]],
 
          [[255, 255, 255],
           [253, 255, 255],
           [255, 255, 254],
           ...,
           [150, 176, 192],
           [144, 173, 189],
           [138, 165, 185]],
 
          ...,
 
          [[255, 255, 255],
           [255, 255, 255],
           [255, 255, 255],
           ...,
           [123, 111, 107],
           [129, 116, 115],
           [134, 117, 120]],
 
          [[255, 255, 255],
           [255, 255, 255],
           [255, 255, 255],
           ...,
           [115, 103, 100],
           [124, 112, 108],
           [138, 119, 116]],
 
          [[255, 255, 255],
           [255, 255

In [23]:
X_train,X_test,y_train,y_test = other_loading_data_proccess(data)

In [24]:
from data_loading import data_loader,transforming

In [25]:
data,X,y,X_train,y_train,X_test,y_test = data_loader()

In [26]:
data,X,y,X_train,y_train,X_test,y_test = load_data()

In [27]:
data = load_data()

In [28]:
data

[[array([[[ 74,  79,  73],
          [ 76,  82,  77],
          [ 89,  94,  89],
          ...,
          [124, 157, 143],
          [105, 140, 126],
          [ 89, 120, 107]],
  
         [[122, 129, 123],
          [ 75,  82,  78],
          [ 77,  83,  80],
          ...,
          [116, 147, 134],
          [107, 143, 127],
          [106, 134, 119]],
  
         [[ 77,  84,  79],
          [ 79,  86,  83],
          [ 63,  70,  67],
          ...,
          [126, 161, 147],
          [ 91, 114, 101],
          [ 82, 109,  95]],
  
         ...,
  
         [[206, 211, 210],
          [187, 191, 190],
          [189, 191, 191],
          ...,
          [202, 203, 200],
          [201, 202, 200],
          [204, 205, 203]],
  
         [[211, 216, 215],
          [189, 191, 191],
          [203, 205, 205],
          ...,
          [190, 191, 189],
          [227, 228, 226],
          [201, 202, 200]],
  
         [[209, 214, 213],
          [203, 205, 205],
          [185, 187, 187

In [29]:
data,X,y,X_train,y_train,X_test,y_test = data

In [30]:
data, X, y, X_train, y_train, X_test, y_test = data

In [31]:
data.shape

In [32]:
np.array(data).shape

(1006, 2)

In [33]:
data[0]

[array([[[ 74,  79,  73],
         [ 76,  82,  77],
         [ 89,  94,  89],
         ...,
         [124, 157, 143],
         [105, 140, 126],
         [ 89, 120, 107]],
 
        [[122, 129, 123],
         [ 75,  82,  78],
         [ 77,  83,  80],
         ...,
         [116, 147, 134],
         [107, 143, 127],
         [106, 134, 119]],
 
        [[ 77,  84,  79],
         [ 79,  86,  83],
         [ 63,  70,  67],
         ...,
         [126, 161, 147],
         [ 91, 114, 101],
         [ 82, 109,  95]],
 
        ...,
 
        [[206, 211, 210],
         [187, 191, 190],
         [189, 191, 191],
         ...,
         [202, 203, 200],
         [201, 202, 200],
         [204, 205, 203]],
 
        [[211, 216, 215],
         [189, 191, 191],
         [203, 205, 205],
         ...,
         [190, 191, 189],
         [227, 228, 226],
         [201, 202, 200]],
 
        [[209, 214, 213],
         [203, 205, 205],
         [185, 187, 187],
         ...,
         [209, 210, 208],
  

In [34]:
data[7]

[array([[[ 24,  33,  72],
         [ 38,  50, 103],
         [ 55,  64, 106],
         ...,
         [ 21,  28,  98],
         [ 18,  30,  88],
         [ 24,  33,  87]],
 
        [[ 25,  42,  66],
         [ 42,  53,  88],
         [ 78,  81, 111],
         ...,
         [ 20,  24,  95],
         [ 22,  27,  89],
         [ 18,  22,  75]],
 
        [[ 34,  59,  68],
         [ 53,  71,  83],
         [ 84,  91, 103],
         ...,
         [ 25,  27,  91],
         [ 25,  26,  89],
         [ 16,  16,  69]],
 
        ...,
 
        [[ 63,  61, 120],
         [ 68,  63, 131],
         [ 71,  68, 130],
         ...,
         [122, 126, 144],
         [208, 214, 236],
         [ 56,  57, 115]],
 
        [[ 60,  58, 117],
         [ 63,  58, 127],
         [ 67,  64, 126],
         ...,
         [185, 192, 207],
         [148, 160, 186],
         [ 56,  58, 114]],
 
        [[ 57,  55, 114],
         [ 59,  53, 123],
         [ 63,  60, 122],
         ...,
         [ 90,  99, 111],
  

In [35]:
data[2]

[array([[[ 72, 103, 126],
         [ 65,  96, 119],
         [ 50,  78, 102],
         ...,
         [ 15,  38,  40],
         [  7,  28,  30],
         [  6,  26,  28]],
 
        [[ 60,  91, 114],
         [ 65,  96, 119],
         [ 62,  92, 117],
         ...,
         [ 12,  33,  34],
         [  5,  26,  28],
         [  6,  27,  28]],
 
        [[ 48,  76, 100],
         [ 41,  69,  93],
         [ 38,  66,  88],
         ...,
         [ 14,  35,  38],
         [  5,  25,  27],
         [  4,  24,  25]],
 
        ...,
 
        [[172, 177, 169],
         [189, 198, 188],
         [194, 201, 194],
         ...,
         [195, 203, 196],
         [192, 200, 193],
         [188, 196, 189]],
 
        [[176, 182, 171],
         [188, 192, 186],
         [194, 201, 194],
         ...,
         [190, 198, 191],
         [193, 201, 194],
         [191, 199, 192]],
 
        [[179, 185, 175],
         [182, 186, 179],
         [192, 199, 192],
         ...,
         [192, 200, 193],
  

In [36]:
data[8]

[array([[[156, 224, 253],
         [157, 225, 253],
         [156, 224, 253],
         ...,
         [117, 176, 198],
         [113, 173, 195],
         [115, 175, 197]],
 
        [[158, 226, 255],
         [158, 226, 255],
         [157, 226, 253],
         ...,
         [113, 173, 195],
         [115, 178, 199],
         [116, 179, 200]],
 
        [[159, 228, 255],
         [159, 228, 255],
         [161, 230, 255],
         ...,
         [120, 180, 202],
         [114, 177, 198],
         [117, 179, 200]],
 
        ...,
 
        [[ 12,  34,  39],
         [ 42,  86,  89],
         [ 59, 115, 122],
         ...,
         [ 60,  90, 147],
         [ 57,  88, 140],
         [ 53,  82, 133]],
 
        [[ 18,  49,  53],
         [ 20,  38,  40],
         [ 38,  87,  89],
         ...,
         [ 47,  84, 140],
         [ 47,  78, 129],
         [ 38,  69, 114]],
 
        [[ 12,  45,  44],
         [  3,  18,  16],
         [ 12,  38,  43],
         ...,
         [ 29,  60, 110],
  

In [37]:
from data_loading import data_loader,transforming

In [38]:
data = load_data()

In [39]:
data[7]

[array([[[255, 254, 255],
         [253, 255, 255],
         [252, 255, 255],
         ...,
         [182, 175, 175],
         [180, 175, 171],
         [187, 187, 183]],
 
        [[253, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [ 72,  51,  53],
         [ 67,  48,  47],
         [ 87,  75,  72]],
 
        [[255, 254, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [ 70,  51,  54],
         [ 57,  44,  42],
         [ 68,  65,  59]],
 
        ...,
 
        [[255, 255, 255],
         [253, 255, 255],
         [255, 255, 254],
         ...,
         [ 37,  26,  50],
         [ 39,  26,  49],
         [ 30,  18,  36]],
 
        [[255, 255, 254],
         [255, 254, 255],
         [255, 255, 255],
         ...,
         [ 33,  21,  44],
         [ 26,  19,  41],
         [ 40,  31,  51]],
 
        [[255, 255, 254],
         [255, 254, 255],
         [255, 255, 255],
         ...,
         [ 37,  25,  56],
  

In [40]:
data[8]

[array([[[ 73,  78,  81],
         [ 78,  82,  87],
         [ 93,  96, 104],
         ...,
         [ 87, 104, 136],
         [ 87, 106, 134],
         [ 87,  99, 121]],
 
        [[ 77,  82,  85],
         [ 87,  91,  96],
         [107, 110, 118],
         ...,
         [ 76,  95, 126],
         [ 75,  92, 121],
         [ 75,  85, 105]],
 
        [[ 85,  90,  92],
         [ 91,  96,  99],
         [111, 115, 120],
         ...,
         [ 72,  91, 118],
         [ 64,  84, 103],
         [ 69,  77,  94]],
 
        ...,
 
        [[ 11,  11,  11],
         [  8,  10,  10],
         [ 98, 103, 102],
         ...,
         [139, 158, 165],
         [145, 164, 171],
         [147, 165, 172]],
 
        [[  8,   8,   8],
         [ 23,  25,  25],
         [ 82,  87,  86],
         ...,
         [142, 168, 175],
         [148, 173, 180],
         [153, 178, 185]],
 
        [[  5,   5,   5],
         [ 62,  63,  63],
         [ 38,  39,  39],
         ...,
         [192, 215, 226],
  

In [41]:
X = []
y = []
for d in data:
    X.append(d[0])
    y.append(d[1])
VAL_SPLIT = 0.25
VAL_SPLIT = len(X) * VAL_SPLIT
X_train = X[:-VAL_SPLIT]
y_train = y[:-VAL_SPLIT]
X_test = X[-VAL_SPLIT:]
y_test = y[-VAL_SPLIT:]
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))
X_train = torch.from_numpy(np.array(X_train))
y_train = torch.from_numpy(np.array(y_train))
X_test = torch.from_numpy(np.array(X_test))
y_test = torch.from_numpy(np.array(y_test))
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

In [42]:
X = []
y = []
for d in data:
    X.append(d[0])
    y.append(d[1])
VAL_SPLIT = 0.25
VAL_SPLIT = len(X) * VAL_SPLIT
VAL_SPLIT = int(VAL_SPLIT)
X_train = X[:-VAL_SPLIT]
y_train = y[:-VAL_SPLIT]
X_test = X[-VAL_SPLIT:]
y_test = y[-VAL_SPLIT:]
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))
X_train = torch.from_numpy(np.array(X_train))
y_train = torch.from_numpy(np.array(y_train))
X_test = torch.from_numpy(np.array(X_test))
y_test = torch.from_numpy(np.array(y_test))
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

In [43]:
from torchvision import models

In [44]:
model = models.resnet18(pretrained=False)

In [45]:
device = torch.device('cuda')

In [46]:
model = models.resnet18(pretrained=True).to(device)

In [47]:
model.to(device)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [48]:
model = model.to(device)

In [49]:
criterion = nn.CrossEntropyLoss()

In [50]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.1)

In [51]:
BATCH_SIZE = 32

In [52]:
EPOCHS = 100

In [53]:
import wandb

In [54]:
PROJECT_NAME = 'Face-Mask-Detection'

In [55]:
wandb.init(project=PROJECT_NAME)